// <auto-generated />
using System;
using DocMaster.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocMaster.Api.Migrations
{
    [DbContext(typeof(DocMasterDbContext))]
    partial class DocMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Bucket", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("buckets", (string)null);
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Chunk", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("object_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("ObjectId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("chunks", (string)null);
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Node", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FreeSpaceBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("free_space_bytes");

                    b.Property<string>("GrpcAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("grpc_address");

                    b.Property<bool>("IsHealthy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_healthy");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ObjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("object_count");

                    b.Property<long?>("TotalSpaceBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_space_bytes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UsedSpaceBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("used_space_bytes");

                    b.HasKey("Id");

                    b.HasIndex("IsHealthy");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Replica", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("node_id");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("object_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("ObjectId");

                    b.HasIndex("ObjectId", "NodeId")
                        .IsUnique();

                    b.ToTable("replicas", (string)null);
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Shard", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("chunk_id");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("node_id");

                    b.Property<int>("ShardIndex")
                        .HasColumnType("integer")
                        .HasColumnName("shard_index");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ChunkId");

                    b.HasIndex("NodeId");

                    b.HasIndex("ChunkId", "ShardIndex")
                        .IsUnique();

                    b.ToTable("shards", (string)null);
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.StorageObject", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("BucketId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("bucket_id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum");

                    b.Property<int>("ChunkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("chunk_count");

                    b.Property<string>("ClaimedContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("claimed_content_type");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("detected_content_type");

                    b.Property<string>("DetectedExtension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("detected_extension");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("key");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_filename");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageStrategy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("storage_strategy");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("BucketId", "Key")
                        .IsUnique();

                    b.ToTable("objects", (string)null);
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Chunk", b =>
                {
                    b.HasOne("DocMaster.Api.Data.Entities.StorageObject", "Object")
                        .WithMany("Chunks")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Replica", b =>
                {
                    b.HasOne("DocMaster.Api.Data.Entities.Node", "Node")
                        .WithMany("Replicas")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocMaster.Api.Data.Entities.StorageObject", "Object")
                        .WithMany("Replicas")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Shard", b =>
                {
                    b.HasOne("DocMaster.Api.Data.Entities.Chunk", "Chunk")
                        .WithMany("Shards")
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocMaster.Api.Data.Entities.Node", "Node")
                        .WithMany("Shards")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chunk");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.StorageObject", b =>
                {
                    b.HasOne("DocMaster.Api.Data.Entities.Bucket", "Bucket")
                        .WithMany("Objects")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Bucket", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Chunk", b =>
                {
                    b.Navigation("Shards");
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.Node", b =>
                {
                    b.Navigation("Replicas");

                    b.Navigation("Shards");
                });

            modelBuilder.Entity("DocMaster.Api.Data.Entities.StorageObject", b =>
                {
                    b.Navigation("Chunks");

                    b.Navigation("Replicas");
                });
#pragma warning restore 612, 618
        }
    }
}
